package org.servlet_demo;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Servlet implementation class Servlet
 */
@WebServlet(name = "ServletDemo", urlPatterns = "/servlet")
public class Servlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	// private int visits = 0;
	public Servlet() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		// response.getWriter().append("Served at: ").append(request.getContextPath());
		// // Generated by IDE.
		// visits++;
		response.setContentType("text/html");
		String fname = request.getParameter("fname");
		String lname = request.getParameter("lname");
		String gender = request.getParameter("gender");
		String address = request.getParameter("address");
		String phone = request.getParameter("phone");
		String city = request.getParameter("city");
		String state = request.getParameter("state");
		String country = request.getParameter("country");
		String continent = request.getParameter("continent");
		String specialization = request.getParameter("specialization");
		String department = request.getParameter("department");
		PrintWriter obj = response.getWriter();
		obj.println("<font color=black>");
		obj.println("<h1>WELCOME " + fname + " " + lname + ".</h1>");
		obj.println("<h2>The Details entered by you are Gender: " + gender + ", Address: " + address + ", Phone Number: "
				+ phone + ", City: " + city + ", State: " + state + ", Country: " + country + ", Continent: " + continent
				+ ", Specialization: " + specialization + ", Department: " + department + "</h2>");
		// obj.println("<h2>You visited "+visits+" no.of times</h2>");
		obj.println("</font>");
		obj.close();
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
